"""empty message

Revision ID: 224fb72090ae
Revises: c7d7d22b5e72
Create Date: 2022-11-29 21:21:56.239513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224fb72090ae'
down_revision = 'c7d7d22b5e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colorojos', sa.String(length=20), nullable=False))
        batch_op.drop_column('colorrojos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colorrojos', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('colorojos')

    # ### end Alembic commands ###
