"""empty message

Revision ID: c7d7d22b5e72
Revises: 1b281bebf08e
Create Date: 2022-11-28 19:19:20.931360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d7d22b5e72'
down_revision = '1b281bebf08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_personaje',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], )
    )
    op.create_table('usuario_planeta',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], )
    )
    op.drop_table('user_planeta')
    op.drop_table('user_personaje')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_personaje',
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], name='user_personaje_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='user_personaje_usuario_id_fkey')
    )
    op.create_table('user_planeta',
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], name='user_planeta_planeta_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='user_planeta_usuario_id_fkey')
    )
    op.drop_table('usuario_planeta')
    op.drop_table('usuario_personaje')
    # ### end Alembic commands ###
